name: "Dry Deploy"
description: "Validates Dart Package for Deployment"
inputs:
  path:
    description: "Build directory path"
    required: false
    default: workspace/build

runs:
  using: "composite"
  steps:
    - name: Validate
      shell: bash
      run: bash "${{ github.action_path }}/../../scripts/validate.sh" ${{ inputs.path }}
    - name: Publish
      shell: bash
      run: bash "${{ github.action_path }}/../../scripts/publish.sh" --buildDir ${{ inputs.path }}
